type LevelsTypes = "basic" | "intermedium" | "advanced";

const technologiesList: Array<String> = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "NodeJS",
  "Express",
  "NestJS",
  "AdonisJS",
  "ReactJS",
  "NextJS",
  "Jest",
  "Tailwind",
  "Git",
  "GitHub",
  "GitBucket",
  "GitLab",
  "GitRunner",
  "Docker",
  "PHP",
  "Laravel",
  "MariaDB",
  "PostgreSQL",
  "OracleDB",
  "MongoDB",
  "React Native",
  "AWS",
  "EC2",
  "S3",
  "RDS",
  "Cloud Watch",
  "Lambda",
  "Route53",
  "API Gateway",
  "IAM",
  "Serverless",
  "Microservices",
  "Monolito",
  "MVC",
  "Prisma",
  "CI/CD",
  "Pipeline",
  "Heroku",
  "Hostinger",
  "Hostgator",
  "SVN",
  "Tortoise",
  "DNS",
  "GCP",
  "Firebase",
  "WebSocket",
  "Webhook",
  "Google Maps API",
  "WhatsApp Business API",
  "Material UI",
  "Python",
];

export default technologiesList;
export type { LevelsTypes };
